# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- task: CmdLine@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      docker build -t $(dockerId)/$(imageName):$(Build.BuildNumber) -t $(dockerId)/$(imageName):latest .
      docker login -u $(dockerId) -p $(dockerPassword)
      docker push $(dockerId)/$(imageName):$(Build.BuildNumber)
      docker push $(dockerId)/$(imageName):latest
    displayName: 'Docker build and push'